### ISSUE TITLE
Custom Colors

### ISSUE THREAD

**Issue by kkrypt0nn** [sphinx-contrib/httpdomain#47]
Hey!

First things first. Thanks for your awesome work 😎

I was wondering if there would one day eventually be a possibility for users to add custom colors for the different request types, for example: red for DELETE, etc.

Thanks in advance

**Comment by Klikini** [comment]
Just add this to your CSS:

```css
.http.delete .descname:first-child {
    color: red;
}
```
That should turn the DELETE text red. To turn the path red too, remove `:first-child`.
